version: 3

dotenv: ['.env']

tasks:
  gen:
    cmds:
      - go generate ./...
  build:
    cmds:
      - CGO_ENABLED=0 GOOS=linux go build -a -gcflags='-N -l' -installsuffix cgo -o main .
  dev:
    cmds:
      - chmod +x ./tmp/main
      - air
  lint:
    cmds:
      - go vet ./...
  default:
    cmds:
      - task gen
      - task build
      - task lint
  install:deps:
    cmds:
      - go mod download
  migrate:apply:
    cmds:
      - |
        atlas migrate apply \
        --dir "file://ent/migrate/migrations" \
        --url $DATABASE_URL
  migrate:status:
    cmds:
      - |
        atlas migrate status \
        --dir "file://ent/migrate/migrations" \
        --url $DATABASE_URL
  migrate:create:
    cmds:
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "Please provide a migration name";
          exit 1;
        fi
        atlas migrate diff initial_migration \
        --dir "file://ent/migrate/migrations" \
        --to "ent://ent/schema" \
        --dev-url $DATABASE_URL

  setup:
    cmds:
      - task install:deps
      - task migrate:apply
      - task migrate:status
