// Code generated by ent, DO NOT EDIT.

package applicantinterest

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the applicantinterest type in the database.
	Label = "applicant_interest"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCategoryID holds the string denoting the category_id field in the database.
	FieldCategoryID = "category_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldApplicantProfileID holds the string denoting the applicant_profile_id field in the database.
	FieldApplicantProfileID = "applicant_profile_id"
	// EdgeApplicantProfile holds the string denoting the applicant_profile edge name in mutations.
	EdgeApplicantProfile = "applicant_profile"
	// EdgeCategory holds the string denoting the category edge name in mutations.
	EdgeCategory = "category"
	// Table holds the table name of the applicantinterest in the database.
	Table = "applicant_interests"
	// ApplicantProfileTable is the table that holds the applicant_profile relation/edge.
	ApplicantProfileTable = "applicant_interests"
	// ApplicantProfileInverseTable is the table name for the ApplicantProfile entity.
	// It exists in this package in order to avoid circular dependency with the "applicantprofile" package.
	ApplicantProfileInverseTable = "applicant_profiles"
	// ApplicantProfileColumn is the table column denoting the applicant_profile relation/edge.
	ApplicantProfileColumn = "applicant_profile_id"
	// CategoryTable is the table that holds the category relation/edge.
	CategoryTable = "applicant_interests"
	// CategoryInverseTable is the table name for the Category entity.
	// It exists in this package in order to avoid circular dependency with the "category" package.
	CategoryInverseTable = "categories"
	// CategoryColumn is the table column denoting the category relation/edge.
	CategoryColumn = "category_id"
)

// Columns holds all SQL columns for applicantinterest fields.
var Columns = []string{
	FieldID,
	FieldCategoryID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldApplicantProfileID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the ApplicantInterest queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCategoryID orders the results by the category_id field.
func ByCategoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategoryID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByApplicantProfileID orders the results by the applicant_profile_id field.
func ByApplicantProfileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApplicantProfileID, opts...).ToFunc()
}

// ByApplicantProfileField orders the results by applicant_profile field.
func ByApplicantProfileField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newApplicantProfileStep(), sql.OrderByField(field, opts...))
	}
}

// ByCategoryField orders the results by category field.
func ByCategoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCategoryStep(), sql.OrderByField(field, opts...))
	}
}
func newApplicantProfileStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ApplicantProfileInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ApplicantProfileTable, ApplicantProfileColumn),
	)
}
func newCategoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CategoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CategoryTable, CategoryColumn),
	)
}
