package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/marianozunino/cc-backend-go/dtos"
	"github.com/marianozunino/cc-backend-go/graph/generated"
)

// Status is the resolver for the status field.
func (r *queryResolver) Status(ctx context.Context, id string) (*dtos.Status, error) {
	return r.GetStatus(ctx, id)
}

// Statuses is the resolver for the statuses field.
func (r *queryResolver) Statuses(ctx context.Context, orderBy *dtos.StatusAggregationInput, take *int, skip *int) (*dtos.PaginatedStatusResponse, error) {
	return r.PaginatedStatuses(ctx, orderBy, take, skip)
}

// Messages implements generated.QueryResolver.
func (r *queryResolver) Messages(ctx context.Context, orderBy *dtos.MessageAggregationInput, take *int, skip *int) (*dtos.PaginatedMessageResponse, error) {
	return r.PaginatedMessages(orderBy, take, skip)
}

// Message implements generated.QueryResolver.
func (r *queryResolver) Message(ctx context.Context, id string) (*dtos.Message, error) {
	return r.GetMessage(id)
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id uuid.UUID) (*dtos.Category, error) {
	return r.GetCategory(id)
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context, orderBy *dtos.CategoryAggregationInput, take *int, skip *int, where *dtos.CategoryWhereInput) (*dtos.PaginatedCategoryResponse, error) {
	return r.PaginatedCategories(orderBy, take, skip, where)
}

// DegreeLevel is the resolver for the degreeLevel field.
func (r *queryResolver) DegreeLevel(ctx context.Context, id uuid.UUID) (*dtos.DegreeLevel, error) {
	fmt.Println("queryResolver.DegreeLevel")
	return r.GetDegreeLevel(id)
}

// DegreeLevels is the resolver for the degreeLevels field.
func (r *queryResolver) DegreeLevels(ctx context.Context, orderBy *dtos.DegreeLevelAggregationInput, take *int, skip *int, where *dtos.DegreeLevelWhereInput) (*dtos.PaginatedDegreeLevelResponse, error) {
	return r.PaginatedDegreeLevels(orderBy, take, skip, where)
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
