// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

type ApplicantProfile struct {
	ent.Schema
}

func (ApplicantProfile) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}),
		field.Time("birthday"),
		field.String("gender"),
		field.String("phone"),
		field.String("address1"),
		field.String("address2"),
		field.String("cv").Optional(),
		field.String("internal_comments"),
		field.Bool("receive_emails"),
		field.Time("created_at").Optional(),
		field.Time("updated_at").Optional(),
		field.Time("deleted_at").Optional(),
		field.UUID("user_id", uuid.UUID{}).Optional().Nillable(),
		field.JSON("extra_skills", struct{}{}).Optional(),
	}

}
func (ApplicantProfile) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("applicant_interests", ApplicantInterest.Type),
		edge.To("applicant_profile_skills", ApplicantProfileSkill.Type),
		edge.From("user", User.Type).Ref("applicant_profiles").Unique().Field("user_id"),
		edge.To("applications", Application.Type),
		edge.To("educations", Education.Type),
		edge.To("languages", Language.Type),
		edge.To("work_experiences", WorkExperience.Type),
	}
}

func (ApplicantProfile) Annotations() []schema.Annotation {
	return nil
}
