// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

type Post struct {
	ent.Schema
}

func (Post) Fields() []ent.Field {
	return []ent.Field{field.UUID("id", uuid.UUID{}),
		field.String("title"),
		field.String("content"),
		field.String("slug").Unique(),
		field.Bool("is_highlighted"),
		field.Bool("is_published"),
		field.Time("published_at").Optional().Nillable(),
		field.String("preview_image").Optional().Nillable(),
		field.UUID("author_id", uuid.UUID{}).Optional().Nillable(),
		field.Time("created_at").Immutable().Default(time.Now),
		field.Time("updated_at").Default(time.Now).UpdateDefault(time.Now),
		field.Time("deleted_at").Optional().Nillable(),
	}
}
func (Post) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("user", User.Type).Ref("posts").Unique().Field("author_id"),
		edge.From("post_category", PostCategory.Type).Ref("posts"),
	}
}
func (Post) Annotations() []schema.Annotation {
	return nil
}
