// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

type WorkExperience struct {
	ent.Schema
}

func (WorkExperience) Fields() []ent.Field {
	return []ent.Field{field.UUID("id", uuid.UUID{}), field.String("company").Optional(), field.String("position").Optional(), field.String("description").Optional(), field.Time("start_date").Optional(), field.Time("end_date").Optional(), field.UUID("applicant_profile_id", uuid.UUID{}).Optional().Nillable(), field.Time("created_at"), field.Time("updated_at"), field.Time("deleted_at").Optional(), field.String("internal_comments").Optional()}
}
func (WorkExperience) Edges() []ent.Edge {
	return []ent.Edge{edge.From("applicant_profile", ApplicantProfile.Type).Ref("work_experiences").Unique().Field("applicant_profile_id")}
}
func (WorkExperience) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "work_experience"}}
}
