// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/marianozunino/cc-backend-go/ent/applicantprofile"
	"github.com/marianozunino/cc-backend-go/ent/predicate"
)

// ApplicantProfileDelete is the builder for deleting a ApplicantProfile entity.
type ApplicantProfileDelete struct {
	config
	hooks    []Hook
	mutation *ApplicantProfileMutation
}

// Where appends a list predicates to the ApplicantProfileDelete builder.
func (apd *ApplicantProfileDelete) Where(ps ...predicate.ApplicantProfile) *ApplicantProfileDelete {
	apd.mutation.Where(ps...)
	return apd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (apd *ApplicantProfileDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, apd.sqlExec, apd.mutation, apd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (apd *ApplicantProfileDelete) ExecX(ctx context.Context) int {
	n, err := apd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (apd *ApplicantProfileDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(applicantprofile.Table, sqlgraph.NewFieldSpec(applicantprofile.FieldID, field.TypeUUID))
	if ps := apd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, apd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	apd.mutation.done = true
	return affected, err
}

// ApplicantProfileDeleteOne is the builder for deleting a single ApplicantProfile entity.
type ApplicantProfileDeleteOne struct {
	apd *ApplicantProfileDelete
}

// Where appends a list predicates to the ApplicantProfileDelete builder.
func (apdo *ApplicantProfileDeleteOne) Where(ps ...predicate.ApplicantProfile) *ApplicantProfileDeleteOne {
	apdo.apd.mutation.Where(ps...)
	return apdo
}

// Exec executes the deletion query.
func (apdo *ApplicantProfileDeleteOne) Exec(ctx context.Context) error {
	n, err := apdo.apd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{applicantprofile.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (apdo *ApplicantProfileDeleteOne) ExecX(ctx context.Context) {
	if err := apdo.Exec(ctx); err != nil {
		panic(err)
	}
}
