// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/marianozunino/jobby/ent/joboffercategory"
	"github.com/marianozunino/jobby/ent/predicate"
)

// JobOfferCategoryDelete is the builder for deleting a JobOfferCategory entity.
type JobOfferCategoryDelete struct {
	config
	hooks    []Hook
	mutation *JobOfferCategoryMutation
}

// Where appends a list predicates to the JobOfferCategoryDelete builder.
func (jocd *JobOfferCategoryDelete) Where(ps ...predicate.JobOfferCategory) *JobOfferCategoryDelete {
	jocd.mutation.Where(ps...)
	return jocd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (jocd *JobOfferCategoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, jocd.sqlExec, jocd.mutation, jocd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (jocd *JobOfferCategoryDelete) ExecX(ctx context.Context) int {
	n, err := jocd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (jocd *JobOfferCategoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(joboffercategory.Table, sqlgraph.NewFieldSpec(joboffercategory.FieldID, field.TypeUUID))
	if ps := jocd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, jocd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	jocd.mutation.done = true
	return affected, err
}

// JobOfferCategoryDeleteOne is the builder for deleting a single JobOfferCategory entity.
type JobOfferCategoryDeleteOne struct {
	jocd *JobOfferCategoryDelete
}

// Where appends a list predicates to the JobOfferCategoryDelete builder.
func (jocdo *JobOfferCategoryDeleteOne) Where(ps ...predicate.JobOfferCategory) *JobOfferCategoryDeleteOne {
	jocdo.jocd.mutation.Where(ps...)
	return jocdo
}

// Exec executes the deletion query.
func (jocdo *JobOfferCategoryDeleteOne) Exec(ctx context.Context) error {
	n, err := jocdo.jocd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{joboffercategory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (jocdo *JobOfferCategoryDeleteOne) ExecX(ctx context.Context) {
	if err := jocdo.Exec(ctx); err != nil {
		panic(err)
	}
}
