// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/marianozunino/cc-backend-go/ent/joboffer"
	"github.com/marianozunino/cc-backend-go/ent/predicate"
	"github.com/marianozunino/cc-backend-go/ent/status"
)

// StatusUpdate is the builder for updating Status entities.
type StatusUpdate struct {
	config
	hooks    []Hook
	mutation *StatusMutation
}

// Where appends a list predicates to the StatusUpdate builder.
func (su *StatusUpdate) Where(ps ...predicate.Status) *StatusUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetName sets the "name" field.
func (su *StatusUpdate) SetName(s string) *StatusUpdate {
	su.mutation.SetName(s)
	return su
}

// SetCreatedAt sets the "created_at" field.
func (su *StatusUpdate) SetCreatedAt(t time.Time) *StatusUpdate {
	su.mutation.SetCreatedAt(t)
	return su
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (su *StatusUpdate) SetNillableCreatedAt(t *time.Time) *StatusUpdate {
	if t != nil {
		su.SetCreatedAt(*t)
	}
	return su
}

// ClearCreatedAt clears the value of the "created_at" field.
func (su *StatusUpdate) ClearCreatedAt() *StatusUpdate {
	su.mutation.ClearCreatedAt()
	return su
}

// SetUpdatedAt sets the "updated_at" field.
func (su *StatusUpdate) SetUpdatedAt(t time.Time) *StatusUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (su *StatusUpdate) SetNillableUpdatedAt(t *time.Time) *StatusUpdate {
	if t != nil {
		su.SetUpdatedAt(*t)
	}
	return su
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (su *StatusUpdate) ClearUpdatedAt() *StatusUpdate {
	su.mutation.ClearUpdatedAt()
	return su
}

// SetDeletedAt sets the "deleted_at" field.
func (su *StatusUpdate) SetDeletedAt(t time.Time) *StatusUpdate {
	su.mutation.SetDeletedAt(t)
	return su
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (su *StatusUpdate) SetNillableDeletedAt(t *time.Time) *StatusUpdate {
	if t != nil {
		su.SetDeletedAt(*t)
	}
	return su
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (su *StatusUpdate) ClearDeletedAt() *StatusUpdate {
	su.mutation.ClearDeletedAt()
	return su
}

// AddJobOfferIDs adds the "job_offers" edge to the JobOffer entity by IDs.
func (su *StatusUpdate) AddJobOfferIDs(ids ...uuid.UUID) *StatusUpdate {
	su.mutation.AddJobOfferIDs(ids...)
	return su
}

// AddJobOffers adds the "job_offers" edges to the JobOffer entity.
func (su *StatusUpdate) AddJobOffers(j ...*JobOffer) *StatusUpdate {
	ids := make([]uuid.UUID, len(j))
	for i := range j {
		ids[i] = j[i].ID
	}
	return su.AddJobOfferIDs(ids...)
}

// Mutation returns the StatusMutation object of the builder.
func (su *StatusUpdate) Mutation() *StatusMutation {
	return su.mutation
}

// ClearJobOffers clears all "job_offers" edges to the JobOffer entity.
func (su *StatusUpdate) ClearJobOffers() *StatusUpdate {
	su.mutation.ClearJobOffers()
	return su
}

// RemoveJobOfferIDs removes the "job_offers" edge to JobOffer entities by IDs.
func (su *StatusUpdate) RemoveJobOfferIDs(ids ...uuid.UUID) *StatusUpdate {
	su.mutation.RemoveJobOfferIDs(ids...)
	return su
}

// RemoveJobOffers removes "job_offers" edges to JobOffer entities.
func (su *StatusUpdate) RemoveJobOffers(j ...*JobOffer) *StatusUpdate {
	ids := make([]uuid.UUID, len(j))
	for i := range j {
		ids[i] = j[i].ID
	}
	return su.RemoveJobOfferIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *StatusUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *StatusUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *StatusUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *StatusUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *StatusUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(status.Table, status.Columns, sqlgraph.NewFieldSpec(status.FieldID, field.TypeUUID))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.SetField(status.FieldName, field.TypeString, value)
	}
	if value, ok := su.mutation.CreatedAt(); ok {
		_spec.SetField(status.FieldCreatedAt, field.TypeTime, value)
	}
	if su.mutation.CreatedAtCleared() {
		_spec.ClearField(status.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.SetField(status.FieldUpdatedAt, field.TypeTime, value)
	}
	if su.mutation.UpdatedAtCleared() {
		_spec.ClearField(status.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := su.mutation.DeletedAt(); ok {
		_spec.SetField(status.FieldDeletedAt, field.TypeTime, value)
	}
	if su.mutation.DeletedAtCleared() {
		_spec.ClearField(status.FieldDeletedAt, field.TypeTime)
	}
	if su.mutation.JobOffersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   status.JobOffersTable,
			Columns: []string{status.JobOffersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(joboffer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedJobOffersIDs(); len(nodes) > 0 && !su.mutation.JobOffersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   status.JobOffersTable,
			Columns: []string{status.JobOffersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(joboffer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.JobOffersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   status.JobOffersTable,
			Columns: []string{status.JobOffersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(joboffer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{status.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// StatusUpdateOne is the builder for updating a single Status entity.
type StatusUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StatusMutation
}

// SetName sets the "name" field.
func (suo *StatusUpdateOne) SetName(s string) *StatusUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetCreatedAt sets the "created_at" field.
func (suo *StatusUpdateOne) SetCreatedAt(t time.Time) *StatusUpdateOne {
	suo.mutation.SetCreatedAt(t)
	return suo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (suo *StatusUpdateOne) SetNillableCreatedAt(t *time.Time) *StatusUpdateOne {
	if t != nil {
		suo.SetCreatedAt(*t)
	}
	return suo
}

// ClearCreatedAt clears the value of the "created_at" field.
func (suo *StatusUpdateOne) ClearCreatedAt() *StatusUpdateOne {
	suo.mutation.ClearCreatedAt()
	return suo
}

// SetUpdatedAt sets the "updated_at" field.
func (suo *StatusUpdateOne) SetUpdatedAt(t time.Time) *StatusUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (suo *StatusUpdateOne) SetNillableUpdatedAt(t *time.Time) *StatusUpdateOne {
	if t != nil {
		suo.SetUpdatedAt(*t)
	}
	return suo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (suo *StatusUpdateOne) ClearUpdatedAt() *StatusUpdateOne {
	suo.mutation.ClearUpdatedAt()
	return suo
}

// SetDeletedAt sets the "deleted_at" field.
func (suo *StatusUpdateOne) SetDeletedAt(t time.Time) *StatusUpdateOne {
	suo.mutation.SetDeletedAt(t)
	return suo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (suo *StatusUpdateOne) SetNillableDeletedAt(t *time.Time) *StatusUpdateOne {
	if t != nil {
		suo.SetDeletedAt(*t)
	}
	return suo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (suo *StatusUpdateOne) ClearDeletedAt() *StatusUpdateOne {
	suo.mutation.ClearDeletedAt()
	return suo
}

// AddJobOfferIDs adds the "job_offers" edge to the JobOffer entity by IDs.
func (suo *StatusUpdateOne) AddJobOfferIDs(ids ...uuid.UUID) *StatusUpdateOne {
	suo.mutation.AddJobOfferIDs(ids...)
	return suo
}

// AddJobOffers adds the "job_offers" edges to the JobOffer entity.
func (suo *StatusUpdateOne) AddJobOffers(j ...*JobOffer) *StatusUpdateOne {
	ids := make([]uuid.UUID, len(j))
	for i := range j {
		ids[i] = j[i].ID
	}
	return suo.AddJobOfferIDs(ids...)
}

// Mutation returns the StatusMutation object of the builder.
func (suo *StatusUpdateOne) Mutation() *StatusMutation {
	return suo.mutation
}

// ClearJobOffers clears all "job_offers" edges to the JobOffer entity.
func (suo *StatusUpdateOne) ClearJobOffers() *StatusUpdateOne {
	suo.mutation.ClearJobOffers()
	return suo
}

// RemoveJobOfferIDs removes the "job_offers" edge to JobOffer entities by IDs.
func (suo *StatusUpdateOne) RemoveJobOfferIDs(ids ...uuid.UUID) *StatusUpdateOne {
	suo.mutation.RemoveJobOfferIDs(ids...)
	return suo
}

// RemoveJobOffers removes "job_offers" edges to JobOffer entities.
func (suo *StatusUpdateOne) RemoveJobOffers(j ...*JobOffer) *StatusUpdateOne {
	ids := make([]uuid.UUID, len(j))
	for i := range j {
		ids[i] = j[i].ID
	}
	return suo.RemoveJobOfferIDs(ids...)
}

// Where appends a list predicates to the StatusUpdate builder.
func (suo *StatusUpdateOne) Where(ps ...predicate.Status) *StatusUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *StatusUpdateOne) Select(field string, fields ...string) *StatusUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Status entity.
func (suo *StatusUpdateOne) Save(ctx context.Context) (*Status, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *StatusUpdateOne) SaveX(ctx context.Context) *Status {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *StatusUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *StatusUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *StatusUpdateOne) sqlSave(ctx context.Context) (_node *Status, err error) {
	_spec := sqlgraph.NewUpdateSpec(status.Table, status.Columns, sqlgraph.NewFieldSpec(status.FieldID, field.TypeUUID))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Status.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, status.FieldID)
		for _, f := range fields {
			if !status.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != status.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.SetField(status.FieldName, field.TypeString, value)
	}
	if value, ok := suo.mutation.CreatedAt(); ok {
		_spec.SetField(status.FieldCreatedAt, field.TypeTime, value)
	}
	if suo.mutation.CreatedAtCleared() {
		_spec.ClearField(status.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.SetField(status.FieldUpdatedAt, field.TypeTime, value)
	}
	if suo.mutation.UpdatedAtCleared() {
		_spec.ClearField(status.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := suo.mutation.DeletedAt(); ok {
		_spec.SetField(status.FieldDeletedAt, field.TypeTime, value)
	}
	if suo.mutation.DeletedAtCleared() {
		_spec.ClearField(status.FieldDeletedAt, field.TypeTime)
	}
	if suo.mutation.JobOffersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   status.JobOffersTable,
			Columns: []string{status.JobOffersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(joboffer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedJobOffersIDs(); len(nodes) > 0 && !suo.mutation.JobOffersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   status.JobOffersTable,
			Columns: []string{status.JobOffersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(joboffer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.JobOffersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   status.JobOffersTable,
			Columns: []string{status.JobOffersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(joboffer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Status{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{status.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
